apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l3-rule-spiffe-based"
spec:
  endpointSelector:
    matchLabels:
      spiffe://example.org/rediscart: ""
  ingress:
  - fromEndpoints:
    - matchLabels:
        spiffe://example.org/cartservice: ""
